### ISSUE TITLE
Reading view destroys the usecase of checkboxes. See video

### ISSUE THREAD

**Issue by mmfs37** [ckRobinson/multi-column-markdown#12] opened 2022-04-04 18:49 UTC
Look at that. 
Never had any problem like that in obsidian. 
Checkmarks work awesome and fine in normal view, but as soon as I enter reading view it checks boxes 5 times higher up. I dont understand

For me this is a dealbreaker and really bad.

![Obsidian_tR3E18qlbg](https://user-images.githubusercontent.com/100991030/161611307-f6b25d09-cf69-4502-b960-f7e6f5ae9fc0.gif)

**Comment by ckRobinson** [comment] 2022-04-05 23:36
Hi, that is extremely unusual. No idea why that would be occurring but I will look into it. I would guess it probably has the same root cause as issue #11 as well.

**Comment by ckRobinson** [comment] 2022-04-21 21:02
This was sharing the same root cause with issue 11. It has been fixed as of 0.5.0 and everything _should_ now function properly.

**Closed** 2022-04-22 12:51 UTC
