### ISSUE TITLE
dataview block can't render

### ISSUE THREAD

**Issue by dengchao0916** [ckRobinson/multi-column-markdown#50] opened 2022-11-06 19:32 UTC
![question](https://user-images.githubusercontent.com/22962925/200190749-dbdf0469-0d48-4768-a3e9-3fc7ebd04631.jpg)

In a simple two column layout I have two dataview block in the two columns.
Problem is that both can not render
I try to run my dataview block independently, they work well
I'm using Obsidian 1.0.3 and Multi-Column Markdown plugin 0.7.3 here.

**Comment by ckRobinson** [comment] 2022-11-12 00:47
Hi there, I released a new build (0.7.4) that should solve this issue, dataview blocks are being properly rendered in all of my tests, but if it is still occurring after you update let me know and I will investigate more.

**Comment by NaturallyAsh** [comment] 2022-11-15 22:30
@ckRobinson Hello. I installed the plugin today and I think I was initially having the same issue. But I put it in reading mode, stared at my screen for a couple of seconds, and then the dataview block rendered correctly. Maybe there's some lagging issues with dataview? But anyway, that was my experience. It's working though.

Obsidian latest, Minimal theme, Mac Pro M1.

**Comment by dengchao0916** [comment] 2022-11-16 01:00
@ckRobinson Hi, I update the plugin, now ,the issue that appeared was the same as @ckRobinson,
In reading mode, it's work sometimes,There will also be a probability of failure

**Comment by towry** [comment] 2022-11-20 02:17
I used this plugin yesterday, have the same issue.

**Comment by ckRobinson** [comment] 2022-12-07 22:31
Yeah, dataview blocks take a bit to load when placed within columns just due to nature of how cross compatibility has had to be implemented. I have made a change in an upcoming build that will reduce the lag a bit. But assuming things are rendering as expected, dataview blocks within columns appear to be working as intended on my end.

**Comment by ckRobinson** [comment] 2023-01-18 03:58
The newest release, 0.7.7, should now render dataview blocks and other content faster. Am closing this issue, feel free to open a new issue if something else comes up.

**Closed by ckRobinson** 2023-01-18 03:58 UTC
