### ISSUE TITLE
It did not render when i embed 2 images in 1 column

### ISSUE THREAD

**Issue by chumido98** [ckRobinson/multi-column-markdown#56] opened 2022-12-07 06:59 UTC
Like screenshot below, please check

![CleanShot 2022-12-07 at 13 59 01@2x](https://user-images.githubusercontent.com/61721378/206110196-486218e6-0357-4bb8-b84d-62e356749a8b.jpg)

**Comment by ckRobinson** [comment] 2022-12-07 22:24
Duplicate of #53.

**Closed by ckRobinson** 2022-12-07 22:24 UTC
