### ISSUE TITLE
[BUG] The tasks can't be displayed correctly.

### ISSUE THREAD

**Issue by Immortal-Sty** [ckRobinson/multi-column-markdown#42] opened 2022-10-14 09:35 UTC
The tasks overlap, and can't be checked.

![](https://s3.bmp.ovh/imgs/2022/10/14/11763b338efc0020.png)

**Comment by ckRobinson** [comment] 2022-12-07 22:12
Duplicate of #54.

**Closed by ckRobinson** 2022-12-07 22:12 UTC
