### ISSUE TITLE
Skipping When Scrolling

### ISSUE THREAD

**Issue by BeeGass** [ckRobinson/multi-column-markdown#15] opened 2022-04-19 21:34 UTC
First off, I really got to say that this is an awesome plugin. You did a really good job with it and it does a ton, really well, straight out of the box so thank you. 

**The issue**
When using the [Admonition plugin](https://github.com/valentine195/obsidian-admonition) or a large amount of markdown I find that there is an issue when scrolling that causes a jumping to occur, likely from the additional return spaces/lines, to quickly jump over the rendered multi-column

**Comment by ckRobinson** [comment] 2022-04-21 21:27
Hey thanks, I'm happy people have found it so useful. 

As far as the issue goes, I believe you are describing one of the known issues I have in the README. From what I have been able to tell this is due to how Obsidian tries to save memory and keep performance up when scrolling a large document. But because the root cause is occurring at a lower level within Obsidian, I have not been able to find a solution yet. It is definitely one of the major headaches I have with the plugin as well. I have a couple potential fixes I've been playing with (some better than others) but so far nothing has seemed to truly fix the issue.

**Comment by ckRobinson** [comment] 2022-08-19 00:07
This issue has now been fixed as of 0.7.0.

**Closed by ckRobinson** 2022-08-19 00:07 UTC
